# Generated by Django 5.1.6 on 2025-05-02 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StuUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('Cpassword', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
