# Generated by Django 5.1.6 on 2025-05-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_stuuser_type_alter_stuuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('Cpassword', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('jobtype', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=50)),
                ('jobDescription', models.CharField(max_length=250)),
                ('type', models.CharField(default='reqUser', max_length=25)),
                ('status', models.CharField(default='reqUser', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
