# Generated by Django 5.1.6 on 2025-05-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_recruiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='jobDescription',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='jobtype',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='title',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='Cpassword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='dashboad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('job_Description', models.TextField()),
                ('type', models.CharField(default='dashboad', max_length=25)),
                ('status', models.CharField(default='dashboad', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
