# Generated by Django 5.1.6 on 2025-05-07 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_recruiter_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiter',
            new_name='recurater',
        ),
    ]
