# Generated by Django 5.1.6 on 2025-05-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_recruiter_recurater'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('admin_post', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('experience', models.IntegerField()),
                ('current_job', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
