# Generated by Django 5.1.6 on 2025-05-10 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_adminapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recuraterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Cpassword', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=25, null='True')),
                ('status', models.CharField(max_length=20, null='True')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='dashboad',
            new_name='dashboadJob',
        ),
        migrations.DeleteModel(
            name='AdminApplication',
        ),
        migrations.DeleteModel(
            name='recurater',
        ),
    ]
