# Generated by Django 5.1.6 on 2025-05-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_recurateruser_rename_dashboad_dashboadjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurateruser',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
