# Generated by Django 5.1.6 on 2025-05-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_recurateruser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboadjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recurateruser'),
        ),
    ]
