# Generated by Django 5.1.6 on 2025-05-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_dashboadjob_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('type', models.CharField(default='dashboard', max_length=25)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recurateruser')),
            ],
        ),
        migrations.DeleteModel(
            name='dashboadJob',
        ),
    ]
