# Generated by Django 5.1.6 on 2025-05-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_dashboardjob_delete_dashboadjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardjob',
            name='status',
        ),
    ]
