# Generated by Django 5.1.6 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_dashboardjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicatioForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('experience_level', models.CharField(max_length=20)),
                ('experience_details', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(max_length=100)),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='aadhaar/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('job_role', models.CharField(max_length=100)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
