# Generated by Django 5.1.6 on 2025-06-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_applicatioform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardjob',
            name='type',
            field=models.CharField(default='dashboad', max_length=25),
        ),
    ]
